# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "armadillo_site" do |app|
    app.vm.box = "centos/7"
    app.vm.provision :shell, path: "aprovisionamiento/centos7_activar_sshd.sh"
    app.vm.network "private_network", ip: "192.168.33.201"
    app.vm.hostname = "armdillosite"
    app.vm.provider "virtualbox" do |v|
        v.memory = 8192
        v.cpus = 2
    end
  end
end